package com.example.sql.dao;

import com.example.sql.model.RunoobTbl;
import com.example.sql.model.RunoobTblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RunoobTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int countByExample(RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int deleteByExample(RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer runoobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int insert(RunoobTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int insertSelective(RunoobTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    List<RunoobTbl> selectByExample(RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    RunoobTbl selectByPrimaryKey(Integer runoobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") RunoobTbl record, @Param("example") RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int updateByExample(@Param("record") RunoobTbl record, @Param("example") RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(RunoobTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    int updateByPrimaryKey(RunoobTbl record);
}