package com.example.sql.dao;

import com.example.sql.model.SettingsInfo;
import com.example.sql.model.SettingsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SettingsInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	int countByExample(SettingsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	int deleteByExample(SettingsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer settingsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	int insert(SettingsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	int insertSelective(SettingsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */List<SettingsInfo> selectByExample(SettingsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	SettingsInfo selectByPrimaryKey(Integer settingsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */int updateByExampleSelective(@Param("record") SettingsInfo record,@Param("example") SettingsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */int updateByExample(@Param("record") SettingsInfo record,@Param("example") SettingsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(SettingsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settings_info
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	int updateByPrimaryKey(SettingsInfo record);
}