package com.sojson.common.dao;

import java.util.List;

import com.sojson.common.model.CountrtyCode;

public interface CountrtyCodeMapper {
	
	List<CountrtyCode> selectAllCountry();

	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counry_code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counry_code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insert(CountrtyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counry_code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insertSelective(CountrtyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counry_code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    CountrtyCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counry_code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKeySelective(CountrtyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counry_code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKey(CountrtyCode record);
}