package com.sojson.common.dao;

import com.sojson.common.model.LogisticsMode;

public interface LogisticsModeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insert(LogisticsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insertSelective(LogisticsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    LogisticsMode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKeySelective(LogisticsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKey(LogisticsMode record);
}