package com.sojson.common.dao;

import com.sojson.common.model.PostageCalcMode;

public interface PostageCalcModeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insert(PostageCalcMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insertSelective(PostageCalcMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    PostageCalcMode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKeySelective(PostageCalcMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKey(PostageCalcMode record);
}