package com.sojson.common.dao;

import com.sojson.common.model.PostageValue;

public interface PostageValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_value
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_value
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insert(PostageValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_value
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insertSelective(PostageValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_value
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    PostageValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_value
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKeySelective(PostageValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_value
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKey(PostageValue record);
}