package com.sojson.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sojson.common.model.PostageCalcMode;
import com.sojson.common.model.URolePermission;

public interface PostageCalcModeMapper {
	
	List<PostageCalcMode> selectByCountryCodeAndServiceMode(@Param("countrycode") String countrycode,
			@Param("servicemode") String servicemode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insert(PostageCalcMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int insertSelective(PostageCalcMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    PostageCalcMode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKeySelective(PostageCalcMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postage_calc_mode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    int updateByPrimaryKey(PostageCalcMode record);
}