package com.sojson.common.dao;

import java.util.List;

import com.sojson.common.model.PostageCalcMode;
import com.sojson.common.model.ServiceMode;

public interface ServiceModeMapper {
	List<ServiceMode> selectAllServiceMode();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_mode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_mode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    int insert(ServiceMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_mode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    int insertSelective(ServiceMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_mode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    ServiceMode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_mode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    int updateByPrimaryKeySelective(ServiceMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_mode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    int updateByPrimaryKey(ServiceMode record);
}