package com.example.sql.model;

import java.util.Date;

public class ProductInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.productid
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.name
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.wifiaddress
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	private String wifiaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.switchstate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	private String switchstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.buzzerstate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	private String buzzerstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.date
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.batterystate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	private String batterystate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.productid
	 * @return  the value of product_info.productid
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.productid
	 * @param productid  the value for product_info.productid
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.name
	 * @return  the value of product_info.name
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.name
	 * @param name  the value for product_info.name
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.wifiaddress
	 * @return  the value of product_info.wifiaddress
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public String getWifiaddress() {
		return wifiaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.wifiaddress
	 * @param wifiaddress  the value for product_info.wifiaddress
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public void setWifiaddress(String wifiaddress) {
		this.wifiaddress = wifiaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.switchstate
	 * @return  the value of product_info.switchstate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public String getSwitchstate() {
		return switchstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.switchstate
	 * @param switchstate  the value for product_info.switchstate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public void setSwitchstate(String switchstate) {
		this.switchstate = switchstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.buzzerstate
	 * @return  the value of product_info.buzzerstate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public String getBuzzerstate() {
		return buzzerstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.buzzerstate
	 * @param buzzerstate  the value for product_info.buzzerstate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public void setBuzzerstate(String buzzerstate) {
		this.buzzerstate = buzzerstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.date
	 * @return  the value of product_info.date
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.date
	 * @param date  the value for product_info.date
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.batterystate
	 * @return  the value of product_info.batterystate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public String getBatterystate() {
		return batterystate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.batterystate
	 * @param batterystate  the value for product_info.batterystate
	 * @mbggenerated  Thu Dec 21 13:00:16 GMT+08:00 2017
	 */
	public void setBatterystate(String batterystate) {
		this.batterystate = batterystate;
	}
}