package com.example.sql.model;

import java.util.Date;

public class RunoobTbl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runoob_tbl.runoob_id
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    private Integer runoobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runoob_tbl.runoob_title
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    private String runoobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runoob_tbl.runoob_author
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    private String runoobAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runoob_tbl.submission_date
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    private Date submissionDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runoob_tbl.runoob_id
     *
     * @return the value of runoob_tbl.runoob_id
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    public Integer getRunoobId() {
        return runoobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runoob_tbl.runoob_id
     *
     * @param runoobId the value for runoob_tbl.runoob_id
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    public void setRunoobId(Integer runoobId) {
        this.runoobId = runoobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runoob_tbl.runoob_title
     *
     * @return the value of runoob_tbl.runoob_title
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    public String getRunoobTitle() {
        return runoobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runoob_tbl.runoob_title
     *
     * @param runoobTitle the value for runoob_tbl.runoob_title
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    public void setRunoobTitle(String runoobTitle) {
        this.runoobTitle = runoobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runoob_tbl.runoob_author
     *
     * @return the value of runoob_tbl.runoob_author
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    public String getRunoobAuthor() {
        return runoobAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runoob_tbl.runoob_author
     *
     * @param runoobAuthor the value for runoob_tbl.runoob_author
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    public void setRunoobAuthor(String runoobAuthor) {
        this.runoobAuthor = runoobAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runoob_tbl.submission_date
     *
     * @return the value of runoob_tbl.submission_date
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    public Date getSubmissionDate() {
        return submissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runoob_tbl.submission_date
     *
     * @param submissionDate the value for runoob_tbl.submission_date
     *
     * @mbggenerated Wed Dec 20 14:49:41 GMT+08:00 2017
     */
    public void setSubmissionDate(Date submissionDate) {
        this.submissionDate = submissionDate;
    }
}