package httptest;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telepphone
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    private String telepphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.productid
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.productname
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    private String productname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telepphone
     *
     * @return the value of user.telepphone
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public String getTelepphone() {
        return telepphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telepphone
     *
     * @param telepphone the value for user.telepphone
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public void setTelepphone(String telepphone) {
        this.telepphone = telepphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.productid
     *
     * @return the value of user.productid
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.productid
     *
     * @param productid the value for user.productid
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.productname
     *
     * @return the value of user.productname
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.productname
     *
     * @param productname the value for user.productname
     *
     * @mbg.generated Sun Dec 24 00:00:09 GMT+08:00 2017
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }
}