package com.sojson.common.model;

public class CountrtyCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counry_code.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counry_code.country
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counry_code.code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counry_code.id
     *
     * @return the value of counry_code.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counry_code.id
     *
     * @param id the value for counry_code.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counry_code.country
     *
     * @return the value of counry_code.country
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counry_code.country
     *
     * @param country the value for counry_code.country
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counry_code.code
     *
     * @return the value of counry_code.code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counry_code.code
     *
     * @param code the value for counry_code.code
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setCode(String code) {
        this.code = code;
    }
}