package com.sojson.common.model;

public class LogisticsMode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_mode.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_mode.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String logistics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_mode.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String servicemode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_mode.id
     *
     * @return the value of logistics_mode.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_mode.id
     *
     * @param id the value for logistics_mode.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_mode.Logistics
     *
     * @return the value of logistics_mode.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getLogistics() {
        return logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_mode.Logistics
     *
     * @param logistics the value for logistics_mode.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setLogistics(String logistics) {
        this.logistics = logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_mode.servicemode
     *
     * @return the value of logistics_mode.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getServicemode() {
        return servicemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_mode.servicemode
     *
     * @param servicemode the value for logistics_mode.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setServicemode(String servicemode) {
        this.servicemode = servicemode;
    }
}