package com.sojson.common.model;

public class PostageCalcMode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_calc_mode.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_calc_mode.countrycode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String countrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_calc_mode.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String servicemode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_calc_mode.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String logistics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_calc_mode.calculation
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String calculation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_calc_mode.id
     *
     * @return the value of postage_calc_mode.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_calc_mode.id
     *
     * @param id the value for postage_calc_mode.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_calc_mode.countrycode
     *
     * @return the value of postage_calc_mode.countrycode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_calc_mode.countrycode
     *
     * @param countrycode the value for postage_calc_mode.countrycode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_calc_mode.servicemode
     *
     * @return the value of postage_calc_mode.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getServicemode() {
        return servicemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_calc_mode.servicemode
     *
     * @param servicemode the value for postage_calc_mode.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setServicemode(String servicemode) {
        this.servicemode = servicemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_calc_mode.Logistics
     *
     * @return the value of postage_calc_mode.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getLogistics() {
        return logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_calc_mode.Logistics
     *
     * @param logistics the value for postage_calc_mode.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setLogistics(String logistics) {
        this.logistics = logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_calc_mode.calculation
     *
     * @return the value of postage_calc_mode.calculation
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getCalculation() {
        return calculation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_calc_mode.calculation
     *
     * @param calculation the value for postage_calc_mode.calculation
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setCalculation(String calculation) {
        this.calculation = calculation;
    }
}