package com.sojson.common.model;

public class PostageValue implements Comparable<PostageValue>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_value.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_value.weight
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private Long weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_value.countrycode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String countrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_value.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String servicemode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_value.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String logistics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postage_value.calculation
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    private String calculation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_value.id
     *
     * @return the value of postage_value.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_value.id
     *
     * @param id the value for postage_value.id
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_value.weight
     *
     * @return the value of postage_value.weight
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_value.weight
     *
     * @param weight the value for postage_value.weight
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setWeight(Long weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_value.countrycode
     *
     * @return the value of postage_value.countrycode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_value.countrycode
     *
     * @param countrycode the value for postage_value.countrycode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_value.servicemode
     *
     * @return the value of postage_value.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getServicemode() {
        return servicemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_value.servicemode
     *
     * @param servicemode the value for postage_value.servicemode
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setServicemode(String servicemode) {
        this.servicemode = servicemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_value.Logistics
     *
     * @return the value of postage_value.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getLogistics() {
        return logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_value.Logistics
     *
     * @param logistics the value for postage_value.Logistics
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setLogistics(String logistics) {
        this.logistics = logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postage_value.calculation
     *
     * @return the value of postage_value.calculation
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public String getCalculation() {
        return calculation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postage_value.calculation
     *
     * @param calculation the value for postage_value.calculation
     *
     * @mbg.generated Sun Jan 10 21:35:57 CST 2021
     */
    public void setCalculation(String calculation) {
        this.calculation = calculation;
    }

	@Override
	public int compareTo(PostageValue o) {
		// TODO Auto-generated method stub
		return ((Double.parseDouble(this.getCalculation()) < Double.parseDouble(o.getCalculation())) ? (-1) : ((Double.parseDouble(this.getCalculation()) == Double.parseDouble(o.getCalculation())) ? 0 : 1));
	}
}