package com.sojson.common.model;

public class ServiceMode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_mode.id
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_mode.servicemode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    private String servicemode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_mode.id
     *
     * @return the value of service_mode.id
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_mode.id
     *
     * @param id the value for service_mode.id
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_mode.servicemode
     *
     * @return the value of service_mode.servicemode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    public String getServicemode() {
        return servicemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_mode.servicemode
     *
     * @param servicemode the value for service_mode.servicemode
     *
     * @mbg.generated Tue Jan 12 03:48:04 CST 2021
     */
    public void setServicemode(String servicemode) {
        this.servicemode = servicemode;
    }
}